config/routes.rb
Ninetab::Application.routes.draw do

  root to: 'static_pages#home'

  scope '(/:locale)', :locale => /en|cs/ do
    match '/:locale'       => 'static_pages#home'
    match '/description'   => 'static_pages#description'
    match '/specification' => 'static_pages#specification'
    match '/contact'       => 'static_pages#contact'
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  def set_locale
    if params[:locale].blank?
      if extract_locale_from_accept_language_header == :cs
        redirect_to '/cs'
      else
        redirect_to '/en'
      end
    end

    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    # if I18n.locale == I18n.default_locale
    #   { locale: '' }
    # else
      { locale: I18n.locale }
    # end
  end

  # extract the language from the clients browser
  def extract_locale_from_accept_language_header
    browser_locale = request.env['HTTP_ACCEPT_LANGUAGE'].try(:scan, /^[a-z]{2}/).try(:first).try(:to_sym)
    if I18n.available_locales.include? browser_locale
      browser_locale
    else
      I18n.default_locale
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :setup_negative_captcha, only: :contact

  VALID_EMAIL_REGEX = /^[\w+\-.]+@[a-z\d\-.]+\.[a-z]+$/i

  def home
  end

  def description    
  end
  
  def specification
  end

  def contact  
    if request.request_method_symbol == :post
      if !@captcha.valid?      
        flash[:alert] = @captcha.error if @captcha.error 
        return
      end

      form_values = @captcha.values
      form_values[:locale] = params[:locale]
 
      if form_values[:email].blank?
        flash[:alert] = t(:ALERT_EMAIL_BLANK)
        return
      elsif form_values[:email] !~ VALID_EMAIL_REGEX
        flash[:alert] = t(:ALERT_EMAIL_FORMAT)
        return
      elsif form_values[:message].blank?
        flash[:alert] = t(:ALERT_MESSAGE_BLANK)
        return
      end

      begin
        ContactMailer.contact_email(form_values).deliver
        flash[:notice] = t(:MAIL_SUCCESS)
        redirect_to contact_path
      rescue
        flash[:alert] = t(:MAIL_ERROR)
      end
    end
  end

private
  def setup_negative_captcha
    @captcha = NegativeCaptcha.new(
      :secret => NEGATIVE_CAPTCHA_SECRET, #A secret key entered in environment.rb. 'rake secret' will give you a good one.
      :spinner => request.remote_ip, 
      :fields => [:subject, :email, :message], #Whatever fields are in your form 
      :params => params
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_class(page)
    if params[:action] == page
      { class: 'selected' }
    end
  end  

  def full_title(page_title)
    base_title = 'Ninetab'
    if page_title.empty?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
  <footer>
    <div>&copy; ninetab.com 2012</div>
    <a href="#"><%= image_tag 'arrow_top.png', alt: '^' %></a>
  </footer>

app/views/layouts/_navigation.html.erb
      <%= image_tag 'logo.png', id: 'logo', alt: 'logo' %>
      <nav>
        <ul>
          <li><%= link_to t(:NAV_HOME), "/#{I18n.locale}", link_class('home') %></li>
          <li><%= link_to t(:NAV_DESCRIPTION), description_path, link_class('description') %></li>
          <li><%= link_to t(:NAV_SPECIFICATION), specification_path, link_class('specification') %></li>
          <li><%= link_to t(:NAV_CONTACT), contact_path, link_class('contact') %></li>
        </ul>
      </nav>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :title) %></title>
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= javascript_include_tag "locale." << params[:locale] << ".js" %>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:200,600&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/favicon.png" />
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
</head>
<body>

<% if params[:action] == 'home' %>
  <header>
    <div id="homepage-top-container">
<%= render 'layouts/navigation' %>
      <div id="top-filling"></div>
      <div id="main-pic" class="flexslider">
        <ul class="slides">
          <li>
            <%= image_tag 'tablet1.jpg', alt: '' %>
            <div class="slide-caption">
              <h1><span>TABLET E8</span></h1>
              <p><%= t(:SLIDE1) %></p>
            </div>
          </li>
          <li>
            <%= image_tag 'tablet2.jpg', alt: '' %>
            <div class="slide-caption">
              <h1><span>TABLET E8</span></h1>
              <p><%= t(:SLIDE1) %></p>
            </div>
          </li>
          <li>
            <%= image_tag 'tablet6.jpg', alt: '' %>
            <div class="slide-caption">
              <h1><span>TABLET E8</span></h1>
              <p><%= t(:SLIDE1) %></p>
            </div>
          </li>
          <li>
            <%= image_tag 'tablet4.jpg', alt: '' %>
            <div class="slide-caption">
              <h1><span>TABLET E8</span></h1>
              <p><%= t(:SLIDE1) %></p>
            </div>
          </li>
          <li>
            <%= image_tag 'tablet5.jpg', alt: '' %>
            <div class="slide-caption">
              <h1><span>TABLET E8</span></h1>
              <p><%= t(:SLIDE1) %></p>
            </div>
          </li>
          <li>
            <%= image_tag 'tablet3.jpg', alt: '' %>
            <div class="slide-caption">
              <h1><span>TABLET E8</span></h1>
              <p><%= t(:SLIDE1) %></p>
            </div>
          </li>
        </ul>
      </div>  
      <div id="en"><%= link_to '', '/en' %></div><div id="cz"><%= link_to '', '/cs' %></div>
    </div>      
  </header>
<%= yield %>

<% else %>
  <header>
    <div id="top-container">
<%= render 'layouts/navigation' %>
      <div id="top-filling"></div>
      <div id="en"><%= link_to '', '/en' %></div><div id="cz"><%= link_to '', '/cs' %></div>
    </div>
 </header>

  <div id="page-content">
<%= yield %>
  </div>
<% end %>

<%= render 'layouts/footer' %>

<%= debug(params) if Rails.env == 'development' %>
</body>
</html>

app/views/static_pages/_description.cs.html.erb
<p>Tablet E8 s operačním systémem Google Android 4.0 (Ice Cream Sandwich) vyniká svým elegantním designem – černou barvou, zadní strana je z pogumovaného materiálu zabraňující vyklouznutí z rukou, tenké provedení - pouze 10 mm.</p>

<p>8“ multi-dotykový kapacitní displej s excelentním rozlišením 1280x768. Kapacita paměti je 8GB a díky paměťovému slotu jí je možné rozšířit až o 32GB. Připojení k internetu zajišťuje WiFi 802.11 b/g/n. Navíc máte k dispozici i  Bluetooth. Periferie tabletu jsou USB, HDMI a 3,5 mm stereo jack. USB slouží pro připojení k PC, nabíjení tabletu, nebo pro připojení USB flash paměti, myši nebo dalších USB zařízení prostřednictvím redukce, která je součástí dodávky. HDMI konektor umožňuje přehrávat obraz na externím zařízení – TV nebo LCD displeji. Tablet je vybaven dvěma kamerami – přední, kterou můžete využít například pro Skype video hovory, a zadní pro pořizování fotografií a videí. Pro dobrý zvuk jsou na zadní straně umístěny stereo reproduktory.</p>

<p>Tablet E8 vám umožní sledovat filmy (včetně flash videí z internetu), přehrávat hudbu a hrát oblíbené hry. Jsou k dispozici aplikace – internetový prohlížeč, mailový klient, kalendář, hodiny, fotoaparát, galerii obrázků a další. Navíc můžete další programy stahovat zdarma nebo nakupovat na Google Play.</p>

app/views/static_pages/_description.en.html.erb
<p>The Tablet E8 running Google Android 4.0 (Ice Cream Sandwich), excels in its elegant design - black color, with a rubberized underside material to prevent slipping. Thin design - only 10 mm.</p>

<p>8" multi-touch capacitive screen has excellent resolution 1280x768 pixels. The memory capacity is 8GB and thanks to the storage slot can be expanded up to 32 GB. Connecting to the Internet provides WiFi 802.11 b/g/n. Bluetooth is also available. The tablet has USB, HDMI and 3.5mm stereo jack peripherals. USB can be used to connect to a PC, for tablet charging, or to connect a USB flash drive, mouse or other USB device through the adapter, which is included. The HDMI connector allows you to play-back the image/video via an external device - TV or LCD display. The tablet comes with two cameras - front (helpful with Skype/video calls) and a back for taking photos and videos. Stereo speakers, located on the back side have been provided for good sound.</p>

<p>The tablet allows you to watch movies (including flash videos via the Internet), play music and play your favorite games. Installed applications - web browser, mail client, calendar, clock, camera, gallery, images and more. In addition, other programs can be downloaded for free or purchased from Google Play.</p>

app/views/static_pages/_specification.cs.html.erb
<table>
  <tr><td>Displej</td><td>8" multi-dotykový kapacitní, rozlišení 1280x768</td></tr>
  <tr class="even"><td>Procesor</td><td>AML8726</td></tr>
  <tr><td>Paměť</td><td>1GB (RAM), 8GB (ROM) </td></tr>
  <tr class="even"><td>Rozšiřující slot</td><td>micro SD/SDHC (až 32 GB)</td></tr>
  <tr><td>WiFi</td><td>802.11 b/g/n</td></tr>
  <tr class="even"><td>Bluetooth</td><td>2.1 EDR</td></tr>
  <tr><td>USB</td><td>micro USB</td></tr>
  <tr class="even"><td>Kamera</td><td>0.3 (přední) /2.0 (zadní) Mega pixel</td></tr>
  <tr><td>Operační systém</td><td>Google Android 4.0 (Ice Cream Sandwich)</td></tr>
  <tr class="even"><td>Audio výstup</td><td>3,5 mm sluchátkový jack, stereo reproduktory</td></tr>
  <tr><td>Gyro sensor</td><td>ano</td></tr>
  <tr class="even"><td>Baterie</td><td>Lithium, 5000 mAh</td></tr>
  <tr><td>Ostatní</td><td>integrovaný mikrofon a reproduktory, napájecí zdroj, micro HDMI konektor (umožňuje přehrávat obraz na externím zařízení – TV, LCD displeji…)</td></tr>
  <tr class="even"><td>Rozměry</td><td>213 x 138 x 10 mm</td></tr>
  <tr><td>Hmotnost</td><td>465g</td></tr>
  <tr class="even"><td>Obsah balení</td><td>USB kabel<br />USB redukce (pro připojení USB flash paměti a další)<br />Napájecí adaptér 230V</td></tr>
</table>

app/views/static_pages/_specification.en.html.erb
<table>
  <tr><td>Display</td><td>8" multi-touch capacitive, resolution 1280x768 pixels</td></tr>
  <tr class="even"><td>Processor</td><td>AML8726</td></tr>
  <tr><td>Memory</td><td>1GB (RAM), 8GB (ROM) </td></tr>
  <tr class="even"><td>Expansion slot</td><td>micro SD/SDHC (až 32 GB)</td></tr>
  <tr><td>WiFi</td><td>802.11 b/g/n</td></tr>
  <tr class="even"><td>Bluetooth</td><td>2.1 EDR</td></tr>
  <tr><td>USB</td><td>micro USB</td></tr>
  <tr class="even"><td>Camera</td><td>0.3 (front) /2.0 (back) Mega pixel</td></tr>
  <tr><td>Operating system</td><td>Google Android 4.0 (Ice Cream Sandwich)</td></tr>
  <tr class="even"><td>Audio output</td><td>3.5 mm stereo jack</td></tr>
  <tr><td>Gyro sensor</td><td>yes</td></tr>
  <tr class="even"><td>Battery</td><td>Lithium, 5000 mAh</td></tr>
  <tr><td>Other</td><td>Integrated microphone and stereo speakers, micro HDMI connector (allows you to view images on an external device – TV or LCD display)</td></tr>
  <tr class="even"><td>Dimensions</td><td>213 x 138 x 10 mm</td></tr>
  <tr><td>Weight</td><td>465g</td></tr>
  <tr class="even"><td>Package contents</td><td>USB cable<br />USB adapter (for connecting USB flash memory, etc.)<br />Power adapter 230V/td></tr>
</table>

app/views/static_pages/contact.html.erb
<% provide :title, t(:HEADER_CONTACT) %>
<h1><%= t :HEADER_CONTACT %></h1>

<% flash.each do |key, value| %>
<div class="<%= "flash-#{key}" %>"><%= value %></div>
<% end %>

<%= form_tag contact_path, method: :post, id: 'contact-form'  do %>
  <%= raw negative_captcha(@captcha) %>
  <div><%= negative_label_tag @captcha, :subject, t(:FORM_SUBJECT) %>
  <%= negative_text_field_tag @captcha, :subject %></div>

  <div><%= negative_label_tag @captcha, :email, t(:FORM_EMAIL), class: :required %>
  <%= negative_text_field_tag @captcha, :email, 'data-validation' => 'validate_email' %>
</div>
  <div><%= negative_label_tag @captcha, :message, t(:FORM_MESSAGE), class: :required %>
  <%= negative_text_area_tag @captcha, :message, 'data-validation' => 'required' %></div>

  <%= submit_tag t(:SEND_MESSAGE_BUTTON) %>
<% end %>

app/views/static_pages/description.html.erb
<% provide :title, t(:HEADER_DESCRIPTION) %>
<h1><%= t :HEADER_DESCRIPTION %></h1>

<%= render "static_pages/description.#{I18n.locale}" %>

app/views/static_pages/home.html.erb
  <div id="homepage-content">
    <section class="first-row">
    <h1 class="f1"><%= t(:H_RESOLUTION) %></h1>
      <p><%= t(:C_RESOLUTION) %></p>
    </section>
    <section class="first-row">
    <h1 class="f2">WiFi</h1>
      <p><%= t(:C_WIFI) %></p>
    </section>
    <section class="first-row">
    <h1 class="f3">Micro SD</h1>
      <p><%= t(:C_MICRO_SD) %></p>
    </section>
    <section class="first-row-last">
    <h1><%= t(:H_IMPRESSIONS) %></h1>
      <%= image_tag 'impressions1.jpg', alt: '' %>
      <%= image_tag 'impressions2.jpg', alt: '' %>
    </section>

    <section class="second-row clear-left">
    <h1 class="s1">USB</h1>
      <p><%= t(:C_USB) %></p>
    </section>
    <section class="second-row">
    <h1 class="s2"><%= t(:H_SLIM) %></h1>
      <p><%= t(:C_SLIM) %></p>
    </section>
    <section class="second-row">
    <h1 class="s3"><%= t(:H_HDMI) %></h1>
      <p><%= t(:C_HDMI) %></p>
    </section>
  </div>

app/views/static_pages/specification.html.erb
<% provide :title, t(:HEADER_SPECIFICATION) %>
<h1><%= t :HEADER_SPECIFICATION %></h1>

<%= render "static_pages/specification.#{I18n.locale}" %>